SELECT DISTINCT
DEV.ID,
DEV.EMAIL,
DEV.FIRST_NAME,
DEV.LAST_NAME

FROM DEVELOPERS AS DEV
JOIN SKILLCODES AS SKILL
ON DEV.SKILL_CODE & SKILL.CODE > 0
WHERE SKILL.NAME IN ('Python', 'C#')
ORDER BY
DEV.ID
